export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_SEARCHED_TERM = 'CHANGE_SEARCHED_TERM';
export const GITHUB_TOKEN_REQUESTED = 'GITHUB_TOKEN_REQUESTED';
export const LOGOUT = 'LOGOUT';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const SEARCH_TERM_REQUESTED = 'SEARCH_TERM_REQUESTED';
export const SORT_COLUMN_BY_ORDER = 'SORT_COLUMN_BY_ORDER';
export const SORT_ITEMS_PER_PAGE = 'SORT_ITEMS_PER_PAGE';

export const FETCH_GITHUB_TOKEN_FAILED = 'FETCH_GITHUB_TOKEN_FAILED';
export const FETCH_GITHUB_TOKEN_FINISHED = 'FETCH_GITHUB_TOKEN_FINISHED';
export const FETCH_GITHUB_TOKEN_STARTED = 'FETCH_GITHUB_TOKEN_STARTED';
export const FETCH_GITHUB_TOKEN_SUCCEEDED = 'FETCH_GITHUB_TOKEN_SUCCEEDED';

export const FETCH_REPOSITORIES_FAILED = 'FETCH_REPOSITORIES_FAILED';
export const FETCH_REPOSITORIES_FINISHED = 'FETCH_REPOSITORIES_FINISHED';
export const FETCH_REPOSITORIES_STARTED = 'FETCH_REPOSITORIES_STARTED';
export const FETCH_REPOSITORIES_SUCCEEDED = 'FETCH_REPOSITORIES_SUCCEEDED';

export const FETCH_GITHUB_USER_FAILED = 'FETCH_GITHUB_USER_FAILED';
export const FETCH_GITHUB_USER_FINISHED = 'FETCH_GITHUB_USER_FINISHED';
export const FETCH_GITHUB_USER_STARTED = 'FETCH_GITHUB_USER_STARTED';
export const FETCH_GITHUB_USER_SUCCEEDED = 'FETCH_GITHUB_USER_SUCCEEDED';

export const FETCH_GITHUB_USER_REQUESTED = 'FETCH_GITHUB_USER_REQUESTED';
export const FETCH_REPOSITORIES_REQUESTED = 'FETCH_REPOSITORIES_REQUESTED';
